import { AlertTriangle, CheckCircle2, Quote } from "lucide-react";
import { Alert, AlertDescription, AlertTitle } from "@/components/ui/alert";
import { Badge } from "@/components/ui/badge";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Progress } from "@/components/ui/progress";
import type { CompetencyKey, Evidence } from "@/lib/domain/assessment";

const labels: Record<CompetencyKey, string> = {
  problem_framing: "Problem framing",
  customer_insight: "Customer insight",
  strategic_coherence: "Strategic coherence",
  adaptability: "Adaptability",
  prioritization: "Prioritization",
  measurement: "Measurement",
  decision_quality: "Decision quality",
};

export type ReportData = {
  total_score: number;
  level: string;
  competency_scores: Record<CompetencyKey, number>;
  deterministic_adjustments: string[];
  contradictions: string[];
  summary: string;
  main_gap: string;
  next_challenge: string;
  evidence: Array<Evidence & { valid?: boolean }>;
};

export function ReportView({
  report,
  mode,
  changes,
}: {
  report: ReportData;
  mode: "live" | "fixture" | "demo";
  changes?: Array<{ field: string; before: string; after: string }>;
}) {
  const visibleEvidence = report.evidence.filter(
    (item) => item.kind !== "positive" || item.valid !== false,
  );
  return (
    <div className="space-y-8">
      {mode !== "live" && (
        <Alert className="border-amber-300/30 bg-amber-300/5">
          <AlertTriangle className="text-amber-300" />
          <AlertTitle>{mode === "demo" ? "Precomputed public demo" : "Fixture result"}</AlertTitle>
          <AlertDescription>This report was not generated by a live model call and must not be represented as one.</AlertDescription>
        </Alert>
      )}
      <section className="grid gap-6 lg:grid-cols-[.72fr_1.28fr]">
        <Card className="border-primary/25 bg-[radial-gradient(circle_at_top,oklch(0.78_0.15_155/0.12),transparent_55%)]">
          <CardContent className="flex h-full flex-col justify-between p-7">
            <div><p className="text-sm text-muted-foreground">Overall score</p><p className="mt-3 font-mono text-7xl tracking-[-0.06em] text-primary">{report.total_score}</p><Badge className="mt-4">{report.level}</Badge></div>
            <p className="mt-8 text-sm leading-6 text-muted-foreground">{report.summary}</p>
          </CardContent>
        </Card>
        <Card>
          <CardHeader><CardTitle>Seven competencies</CardTitle></CardHeader>
          <CardContent className="space-y-4">
            {Object.entries(labels).map(([key, label]) => {
              const value = report.competency_scores[key as CompetencyKey];
              return <div key={key}><div className="mb-2 flex justify-between text-sm"><span>{label}</span><span className="font-mono text-muted-foreground">{value}</span></div><Progress value={value} /></div>;
            })}
          </CardContent>
        </Card>
      </section>

      <section>
        <h2 className="text-2xl tracking-tight">Verified evidence</h2>
        <p className="mt-2 text-sm text-muted-foreground">Positive findings appear only when the exact quote is present at the recorded source path.</p>
        <div className="mt-5 grid gap-4 md:grid-cols-2">
          {visibleEvidence.map((item, index) => (
            <Card key={item.source_path + index}>
              <CardContent className="p-5">
                <div className="flex items-center justify-between gap-3"><Badge variant={item.kind === "positive" ? "default" : "outline"}>{labels[item.competency]}</Badge>{item.valid !== false && <CheckCircle2 className="size-4 text-primary" />}</div>
                <blockquote className="mt-4 border-l-2 border-primary/50 pl-4 text-sm leading-6">“{item.exact_quote}”</blockquote>
                <p className="mt-4 text-sm leading-6 text-muted-foreground">{item.explanation}</p>
                <p className="mt-3 font-mono text-[10px] text-muted-foreground">{item.source_path}</p>
              </CardContent>
            </Card>
          ))}
        </div>
      </section>

      {changes && changes.length > 0 && (
        <section>
          <h2 className="text-2xl tracking-tight">Before → after</h2>
          <div className="mt-5 space-y-4">
            {changes.map((change) => (
              <Card key={change.field}><CardContent className="grid gap-4 p-5 md:grid-cols-[120px_1fr_1fr]"><p className="font-mono text-xs uppercase text-primary">{change.field.replaceAll("_", " ")}</p><p className="text-sm leading-6 text-muted-foreground">{change.before}</p><p className="text-sm leading-6">{change.after}</p></CardContent></Card>
            ))}
          </div>
        </section>
      )}

      <section className="grid gap-5 md:grid-cols-2">
        <Card><CardHeader><CardTitle className="flex items-center gap-2"><AlertTriangle className="size-5 text-amber-300" />Main gap</CardTitle></CardHeader><CardContent><p className="leading-7 text-muted-foreground">{report.main_gap}</p></CardContent></Card>
        <Card className="border-primary/25"><CardHeader><CardTitle className="flex items-center gap-2"><Quote className="size-5 text-primary" />Next challenge</CardTitle></CardHeader><CardContent><p className="leading-7 text-muted-foreground">{report.next_challenge}</p></CardContent></Card>
      </section>

      {(report.contradictions.length > 0 || report.deterministic_adjustments.length > 0) && (
        <Card><CardHeader><CardTitle>Audit notes</CardTitle></CardHeader><CardContent className="space-y-3 text-sm text-muted-foreground">{[...report.contradictions, ...report.deterministic_adjustments].map((item) => <p key={item}>• {item}</p>)}</CardContent></Card>
      )}
    </div>
  );
}

